import CustomYearInput from "@/Components/CustomYearInput";
import PanelLayout, { LayoutType } from "@/Layouts/PanelLayout";
import { useEffect } from "react";
import { useState } from "react";
import { Card } from "react-bootstrap";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

export default function AnnualReport({ auth }) {
  const [selectedYear, setSelectedYear] = useState("");

  const handleYearChange = (date) => {
    setSelectedYear(date);
  };

  const handleSubmission = () => {
    axios
      .post(route("admin.annual_reports.create"), {
        data: { year: selectedYear, user: auth.user.id },
      })
      .then((data) => console.log(data));
  };

  return (
    <PanelLayout
      layout={LayoutType.SUPER_ADMIN}
      defaultActiveLink="generated_reports_annually"
    >
      <div className="content-wrapper">
        <div className="bg-white p-6">
          <button
            onClick={() => {
              handleSubmission();
            }}
            className="transition bg-indigo-600 text-white px-3 py-2 text-sm font-medium shadow hover:bg-indigo-400 rounded-md"
          >
            General annual report
          </button>
          <div className="flex bg-white flex-col">
            <div>
              <p className="font-bold">Select Date</p>
            </div>
            <DatePicker
              selected={selectedYear}
              onChange={handleYearChange}
              dateFormat="yyyy"
              showYearPicker
              scrollableYearDropdown
              yearDropdownItemNumber={10} // Adjust the number of visible years in the dropdown
            />
          </div>

          <table className="mt-4 w-full">
            <thead className="">
              <tr className="[&>th]:text-slate-500 [&>th]:bg-slate-50 [&>th]:border-l [&>th:first-child]:border-0 [&>th]:px-4 [&>th]:py-2 border-b [&>th]:text-sm [&>th]:font-bold">
                <th>Report Year</th>
                <th>Generated By</th>
                <th>Generated At</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
              <tr className="[&>td]:text-sm [&>td]:border-l [&>td:first-child]:border-0 [&>td]:px-4 [&>td]:py-2.5">
                <td>2023</td>
                <td>John Aeron</td>
                <td>Dummy</td>
                <td className="flex items-center">Delete Show</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </PanelLayout>
  );
}
