import CustomYearInput from "@/Components/CustomYearInput";
import PanelLayout, { LayoutType } from "@/Layouts/PanelLayout";
import { Card } from "react-bootstrap";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

export default function AnnualReport() {
  return (
    <PanelLayout
      layout={LayoutType.SUPER_ADMIN}
      defaultActiveLink="generated_reports_annually"
    >
      <div className="content-wrapper">
        <div className="bg-white p-6">
          <table className="mt-4 w-full">
            <thead className="">
              <tr className="[&>th]:text-slate-500 [&>th]:bg-slate-50 [&>th]:border-l [&>th:first-child]:border-0 [&>th]:px-4 [&>th]:py-2 border-b [&>th]:text-sm [&>th]:font-bold">
                <th>Report Year</th>
                <th>Generated By</th>
                <th>Generated At</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>
              <tr className="[&>td]:text-sm [&>td]:border-l [&>td:first-child]:border-0 [&>td]:px-4 [&>td]:py-2.5">
                <td>2023</td>
                <td>John Aeron</td>
                <td>Dummy</td>
                <td className="flex items-center">Delete Show</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </PanelLayout>
  );
}
